(function(g){var window=this;'use strict';var oSa=function(a,b){return g.De(a,b)},pSa=function(a,b){b=b instanceof g.Cf?b:g.If(b,/^data:image\//i.test(b));
a.src=g.Df(b)},O6=function(a){g.Yj(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Ra()).toString(36));
return a},P6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.dk(a.u,b,c)},qSa=function(a){if(a instanceof g.ko)return a;
if("function"==typeof a.Mg)return a.Mg(!1);if(g.Ma(a)){var b=0,c=new g.ko;c.wj=function(){for(;;){if(b>=a.length)throw g.br;if(b in a)return a[b++];b++}};
return c}throw Error("Not implemented");},rSa=function(a,b,c){if(g.Ma(a))try{g.kc(a,b,c)}catch(d){if(d!==g.br)throw d;
}else{a=qSa(a);try{for(;;)b.call(c,a.wj(),void 0,a)}catch(d){if(d!==g.br)throw d;}}},sSa=function(a,b){var c=[];
rSa(b,function(d){try{var e=g.Cr.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Br(e)&&c.push(d)},a);
return c},tSa=function(a,b){sSa(a,b).forEach(function(c){g.Cr.prototype.remove.call(this,c)},a)},uSa=function(a){if(a.va){if(a.va.locationOverrideToken)return{locationOverrideToken:a.va.locationOverrideToken};
if(null!=a.va.latitudeE7&&null!=a.va.longitudeE7)return{latitudeE7:a.va.latitudeE7,longitudeE7:a.va.longitudeE7}}return null},vSa=function(a,b){g.Pb(a,b)||a.push(b)},Q6=function(a){var b=0,c;
for(c in a)b++;return b},wSa=function(a){try{return g.C.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},R6=function(a){if(g.C.JSON)try{return g.C.JSON.parse(a)}catch(b){}return wSa(a)},xSa=function(a,b,c,d){var e=new g.Qj(null,void 0);
a&&g.Rj(e,a);b&&g.Sj(e,b);c&&g.Tj(e,c);d&&(e.K=d);return e},S6=function(a,b){g.jv[a]=!0;
var c=g.hv();c&&c.publish.apply(c,arguments);g.jv[a]=!1},T6=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.cr;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",ySa(this,a.capabilities||""),zSa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},ySa=function(a,b){a.capabilities.clear();
g.Jo(b.split(","),g.Qa(oSa,ASa)).forEach(function(c){a.capabilities.add(c)})},zSa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},U6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},V6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},BSa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},CSa=function(a){return new U6(a)},DSa=function(a){return Array.isArray(a)?g.tm(a,CSa):[]},W6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},X6=function(a){return Array.isArray(a)?"["+g.tm(a,W6).join(",")+"]":"null"},Y6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},ESa=function(a){return g.tm(a,function(b){return{key:b.id,
name:b.name}})},Z6=function(a,b){return g.Mb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},$6=function(a,b){return g.Mb(a,function(c){return V6(c,b)})},FSa=function(){var a=(0,g.Qy)();
a&&tSa(a,a.i.Mg(!0))},a7=function(){var a=g.Ty("yt-remote-connected-devices")||[];
g.fc(a);return a},GSa=function(a){if(g.Qb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.tm(a,function(d,e){return 0==e?d:d.substring(c.length)})},HSa=function(a){g.Sy("yt-remote-connected-devices",a,86400)},c7=function(){if(b7)return b7;
var a=g.Ty("yt-remote-device-id");a||(a=Y6(),g.Sy("yt-remote-device-id",a,31536E3));for(var b=a7(),c=1,d=a;g.Pb(b,d);)c++,d=a+"#"+c;return b7=d},d7=function(){var a=a7(),b=c7();
g.Pb(a,b);g.Vy()&&g.hc(a,b);a=GSa(a);if(g.Qb(a))try{g.Ut("remote_sid")}catch(c){}else try{g.St("remote_sid",a.join(","),-1)}catch(c){}},ISa=function(){return g.Ty("yt-remote-session-browser-channel")},JSa=function(){return g.Ty("yt-remote-local-screens")||[]},KSa=function(){g.Sy("yt-remote-lounge-token-expiration",!0,86400)},LSa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.tm(JSa(),function(d){return d.loungeToken}),c=g.tm(a,function(d){return d.loungeToken});
g.um(c,function(d){return!g.Pb(b,d)})&&KSa();
g.Sy("yt-remote-local-screens",a,31536E3)},MSa=function(a,b){g.Sy("yt-remote-session-browser-channel",a);
g.Sy("yt-remote-session-screen-id",b);a=a7();b=c7();g.Pb(a,b)||a.push(b);HSa(a);d7()},e7=function(a){a||(g.Uy("yt-remote-session-screen-id"),g.Uy("yt-remote-session-video-id"));
d7();a=a7();g.Tb(a,c7());HSa(a)},NSa=function(){if(!f7){var a=g.Mr();
a&&(f7=new g.wr(a))}},OSa=function(){NSa();
return f7?!!f7.get("yt-remote-use-staging-server"):!1},g7=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},PSa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},QSa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},h7=function(a){a.length?RSa(a.shift(),function(){h7(a)}):i7()},SSa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},RSa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.Yk(d,g.kr(a));(document.head||document.documentElement).appendChild(d)},TSa=function(){var a=g7(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},i7=function(){var a=QSa();
a&&a(!1,"No cast extension found")},j7=function(){if(USa){var a=2,b=QSa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;RSa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",i7,c)}},VSa=function(){j7();
var a=TSa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");h7(a)},XSa=function(){j7();
var a=TSa();a.push.apply(a,g.la(WSa.map(SSa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");h7(a)},k7=function(a,b,c){g.H.call(this);
this.I=null!=c?(0,g.D)(a,c):a;this.Uf=b;this.D=(0,g.D)(this.qQ,this);this.i=!1;this.u=0;this.B=this.Lb=null;this.C=[]},l7=function(a,b,c){g.H.call(this);
this.C=null!=c?a.bind(c):a;this.Uf=b;this.B=null;this.i=!1;this.u=0;this.Lb=null},m7=function(a){a.Lb=g.Ch(function(){a.Lb=null;
a.i&&!a.u&&(a.i=!1,m7(a))},a.Uf);
var b=a.B;a.B=null;a.C.apply(null,b)},n7=function(){},o7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.C.setTimeout(function(){a()},b)},q7=function(a){p7.dispatchEvent(new YSa(p7,a))},YSa=function(a,b){g.ke.call(this,"statevent",a);
this.stat=b},r7=function(a,b,c,d){this.i=a;
this.B=b;this.S=c;this.K=d||1;this.u=45E3;this.C=new g.ek(this);this.I=new g.Bh;this.I.setInterval(250)},$Sa=function(a,b,c){a.Et=1;
a.Sm=O6(b.clone());a.wq=c;a.D=!0;ZSa(a,null)},s7=function(a,b,c,d,e){a.Et=1;
a.Sm=O6(b.clone());a.wq=null;a.D=c;e&&(a.IN=!1);ZSa(a,d)},ZSa=function(a,b){a.kt=Date.now();
t7(a);a.Bo=a.Sm.clone();P6(a.Bo,"t",a.K);a.uB=0;a.Nf=a.i.mD(a.i.kx()?b:null);0<a.hC&&(a.HA=new l7((0,g.D)(a.MO,a,a.Nf),a.hC));a.C.Ra(a.Nf,"readystatechange",a.rQ);b=a.Vo?g.Ke(a.Vo):{};a.wq?(a.rB="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Nf.send(a.Bo,a.rB,a.wq,b)):(a.rB="GET",a.IN&&!g.Jg&&(b.Connection="close"),a.Nf.send(a.Bo,a.rB,null,b));a.i.xj(1)},bTa=function(a,b){var c=a.uB,d=b.indexOf("\n",c);
if(-1==d)return u7;c=Number(b.substring(c,d));if(isNaN(c))return aTa;d+=1;if(d+c>b.length)return u7;b=b.substr(d,c);a.uB=d+c;return b},dTa=function(a,b){a.kt=Date.now();
t7(a);var c=b?window.location.hostname:"";a.Bo=a.Sm.clone();g.Yj(a.Bo,"DOMAIN",c);g.Yj(a.Bo,"t",a.K);try{a.Nj=new ActiveXObject("htmlfile")}catch(m){v7(a);a.Mm=7;q7(22);w7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in x7)f=x7[f];else if(f in cTa)f=x7[f]=cTa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
x7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Zf(g.uf("b/12014412"),d);a.Nj.open();a.Nj.write(g.Vf(c));a.Nj.close();a.Nj.parentWindow.m=(0,g.D)(a.lW,a);a.Nj.parentWindow.d=(0,g.D)(a.SM,a,!0);a.Nj.parentWindow.rpcClose=(0,g.D)(a.SM,a,!1);c=a.Nj.createElement("DIV");a.Nj.parentWindow.document.body.appendChild(c);d=g.Hf(a.Bo.toString());d=g.pg(g.Df(d));d=g.Zf(g.uf("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ag(c,d);a.i.xj(1)},t7=function(a){a.cH=Date.now()+
a.u;
eTa(a,a.u)},eTa=function(a,b){if(null!=a.Pt)throw Error("WatchDog timer not null");
a.Pt=o7((0,g.D)(a.sW,a),b)},y7=function(a){a.Pt&&(g.C.clearTimeout(a.Pt),a.Pt=null)},w7=function(a){a.i.rf()||a.pp||a.i.Ux(a)},v7=function(a){y7(a);
g.he(a.HA);a.HA=null;a.I.stop();g.gk(a.C);if(a.Nf){var b=a.Nf;a.Nf=null;b.abort();b.dispose()}a.Nj&&(a.Nj=null)},z7=function(a,b){try{a.i.KM(a,b),a.i.xj(4)}catch(c){}},gTa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;fTa(a,b,function(h){h?c(!0):g.C.setTimeout(function(){gTa(a,b,c,d,f)},f)})}},fTa=function(a,b,c){var d=new Image;
d.onload=function(){try{A7(d),c(!0)}catch(e){}};
d.onerror=function(){try{A7(d),c(!1)}catch(e){}};
d.onabort=function(){try{A7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{A7(d),c(!1)}catch(e){}};
g.C.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
pSa(d,a)},A7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},hTa=function(a){this.i=a;
this.u=new n7},iTa=function(a){var b=B7(a.i,a.Mu,"/mail/images/cleardot.gif");
O6(b);gTa(b.toString(),5E3,(0,g.D)(a.iR,a),3,2E3);a.xj(1)},D7=function(a){var b=a.i.X;
if(null!=b)q7(5),b?(q7(11),C7(a.i,a,!1)):(q7(12),C7(a.i,a,!0));else if(a.ph=new r7(a,void 0,void 0,void 0),a.ph.Vo=a.iC,b=a.i,b=B7(b,b.kx()?a.wu:null,a.jC),q7(5),!g.yc||g.sc(10))P6(b,"TYPE","xmlhttp"),s7(a.ph,b,!1,a.wu,!1);else{P6(b,"TYPE","html");var c=a.ph;a=!!a.wu;c.Et=3;c.Sm=O6(b.clone());dTa(c,a)}},E7=function(a,b,c){this.i=1;
this.u=[];this.C=[];this.D=new n7;this.S=a||null;this.X=null!=b?b:null;this.I=c||!1},jTa=function(a,b){this.i=a;
this.map=b;this.context=null},kTa=function(a,b,c,d){g.ke.call(this,"timingevent",a);
this.size=b;this.Yw=d},lTa=function(a){g.ke.call(this,"serverreachability",a)},oTa=function(a){mTa(a);
if(3==a.i){var b=a.nw++,c=a.Oy.clone();g.Yj(c,"SID",a.B);g.Yj(c,"RID",b);g.Yj(c,"TYPE","terminate");F7(a,c);b=new r7(a,a.B,b,void 0);b.Et=2;b.Sm=O6(c.clone());pSa(new Image,b.Sm.toString());b.kt=Date.now();t7(b)}nTa(a)},pTa=function(a){a.IR(1,0);
a.Oy=B7(a,null,a.kC);G7(a)},mTa=function(a){a.Wm&&(a.Wm.abort(),a.Wm=null);
a.Ke&&(a.Ke.cancel(),a.Ke=null);a.Cl&&(g.C.clearTimeout(a.Cl),a.Cl=null);H7(a);a.Xg&&(a.Xg.cancel(),a.Xg=null);a.qn&&(g.C.clearTimeout(a.qn),a.qn=null)},qTa=function(a,b){if(0==a.i)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new jTa(a.nT++,b));2!=a.i&&3!=a.i||G7(a)},rTa=function(a){var b=0;
a.Ke&&b++;a.Xg&&b++;return b},G7=function(a){a.Xg||a.qn||(a.qn=o7((0,g.D)(a.QM,a),0),a.Yr=0)},tTa=function(a,b){if(1==a.i){if(!b){a.nw=Math.floor(1E5*Math.random());
b=a.nw++;var c=new r7(a,"",b,void 0);c.Vo=a.Yj;var d=I7(a),e=a.Oy.clone();g.Yj(e,"RID",b);g.Yj(e,"CVER","1");F7(a,e);$Sa(c,e,d);a.Xg=c;a.i=2}}else 3==a.i&&(b?sTa(a,b):0==a.u.length||a.Xg||sTa(a))},sTa=function(a,b){if(b)if(6<a.qp){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.nw-1;b=I7(a)}else c=b.S,b=b.wq;else c=a.nw++,b=I7(a);var d=a.Oy.clone();g.Yj(d,"SID",a.B);g.Yj(d,"RID",c);g.Yj(d,"AID",a.Is);F7(a,d);c=new r7(a,a.B,c,a.Yr+1);c.Vo=a.Yj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Xg=c;$Sa(c,d,b)},F7=function(a,b){a.Of&&(a=a.Of.gK())&&g.se(a,function(c,d){g.Yj(b,d,c)})},I7=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.qp&&0<b){var d=a.u[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Wq:e.Wq},f++){e.Wq=a.u[f].i;var h=a.u[f].map;e.Wq=6>=a.qp?f:e.Wq-d;try{g.se(h,function(l){return function(m,n){c.push("req"+l.Wq+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Wq+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},uTa=function(a){a.Ke||a.Cl||(a.K=1,a.Cl=o7((0,g.D)(a.PM,a),0),a.Ir=0)},J7=function(a){if(a.Ke||a.Cl||3<=a.Ir)return!1;
a.K++;a.Cl=o7((0,g.D)(a.PM,a),vTa(a,a.Ir));a.Ir++;return!0},C7=function(a,b,c){a.pB=c;
a.Zj=b.ol;a.I||pTa(a)},H7=function(a){null!=a.Ap&&(g.C.clearTimeout(a.Ap),a.Ap=null)},vTa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},K7=function(a,b){if(2==b||9==b){var c=null;
a.Of&&(c=null);var d=(0,g.D)(a.vX,a);c||(c=new g.Qj("//www.google.com/images/cleardot.gif"),O6(c));fTa(c.toString(),1E4,d)}else q7(2);wTa(a,b)},wTa=function(a,b){a.i=0;
a.Of&&a.Of.uJ(b);nTa(a);mTa(a)},nTa=function(a){a.i=0;
a.Zj=-1;if(a.Of)if(0==a.C.length&&0==a.u.length)a.Of.ZC();else{g.Wb(a.C);var b=g.Wb(a.u);a.C.length=0;a.u.length=0;a.Of.ZC(b)}},B7=function(a,b,c){var d=g.Zj(c);
if(""!=d.i)b&&g.Sj(d,b+"."+d.i),g.Tj(d,d.B);else{var e=window.location;d=xSa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.uv&&g.se(a.uv,function(f,h){g.Yj(d,h,f)});
g.Yj(d,"VER",a.qp);F7(a,d);return d},xTa=function(){},yTa=function(){this.i=[];
this.u=[]},zTa=function(a,b){this.action=a;
this.params=b||{}},L7=function(a,b){g.H.call(this);
this.i=new g.J(this.cW,0,this);g.I(this,this.i);this.Uf=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.D)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.D)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},M7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.va=a;this.I=b;this.B=new g.vr;this.u=new L7(this.ZW,this);this.i=null;this.ma=!1;this.D=null;this.X="";this.S=this.C=0;this.K=[];this.Aa=c;this.Z=d;this.Ba=e},ATa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.pB,sessionId:a.i.B,arrayId:a.i.Is}},BTa=function(a,b){a.S=b||0;
a.u.stop();N7(a);a.i&&(3==a.i.getState()&&tTa(a.i),oTa(a.i));a.S=0},O7=function(a){return!!a.i&&3==a.i.getState()},N7=function(a){if(a.i){var b=a.Z(),c=a.i.Yj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Yj=c}},P7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.ki(4,a))||"";b&&(this.port=":"+b);this.domain=g.li(a)||"";a=g.Ab;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.xb(a,"10.0")&&(this.u=!1))},Q7=function(a,b){var c=a.i;
a.u&&(c="https://"+a.domain+a.port+a.i);return g.wi(c+b,{})},R7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.C,d,!0),onError:g.Qa(a.B,e),onTimeout:g.Qa(a.D,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Ht(b,a)},FTa=function(){var a=CTa;
DTa();S7.push(a);ETa()},T7=function(a,b){DTa();
var c=GTa(a,String(b));g.Qb(S7)?HTa(c):(ETa(),g.kc(S7,function(d){d(c)}))},DTa=function(){S7||(S7=g.Ia("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",S7,void 0))},HTa=function(a){var b=(U7+1)%50;
U7=b;V7[b]=a;W7||(W7=49==b)},ETa=function(){var a=S7;
if(V7[0]){var b=W7?U7:-1;do{b=(b+1)%50;var c=V7[b];g.kc(a,function(d){d(c)})}while(b!=U7);
V7=Array(50);U7=-1;W7=!1}},GTa=function(a,b){var c=(Date.now()-ITa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},X7=function(a){g.ey.call(this);
this.I=a;this.screens=[]},JTa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},KTa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Jo(a.screens,function(f){return!!Z6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=JTa(a,b[d])||c;return c},LTa=function(a,b){var c=a.screens.length;
a.screens=g.Jo(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},Y7=function(a,b,c,d,e){g.ey.call(this);
this.B=a;this.K=b;this.C=c;this.I=d;this.D=e;this.u=0;this.i=null;this.Lb=NaN},$7=function(a){X7.call(this,"LocalScreenService");
this.u=a;this.i=NaN;Z7(this);this.info("Initializing with "+X6(this.screens))},MTa=function(a){if(a.screens.length){var b=g.tm(a.screens,function(d){return d.id}),c=Q7(a.u,"/pairing/get_lounge_token_batch");
R7(a.u,c,{screen_ids:b.join(",")},(0,g.D)(a.fS,a),(0,g.D)(a.eS,a))}},Z7=function(a){if(g.P("deprecate_pair_servlet_enabled"))return KTa(a,[]);
var b=DSa(JSa());b=g.Jo(b,function(c){return!c.uuid});
return KTa(a,b)},a8=function(a,b){LSa(g.tm(a.screens,BSa));
b&&KSa()},c8=function(a,b){g.ey.call(this);
this.I=b;b=(b=g.Ty("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.I(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.Pb(b,h)}this.i=c;this.D=a;this.B=this.C=NaN;this.u=null;b8("Initialized with "+g.bi(this.i))},d8=function(a,b,c){var d=Q7(a.D,"/pairing/get_screen_availability");
R7(a.D,d,{lounge_token:b.token},(0,g.D)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.D)(function(){c(!1)},a))},e8=function(a,b){a:if(Q6(b)!=Q6(a.i))var c=!1;
else{c=g.Ae(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(b8("Updated online screens: "+g.bi(a.i)),a.i=b,a.ea("screenChange"));NTa(a)},f8=function(a){isNaN(a.B)||g.Bt(a.B);
a.B=g.zt((0,g.D)(a.SF,a),0<a.C&&a.C<g.Ra()?2E4:1E4)},b8=function(a){T7("OnlineScreenService",a)},OTa=function(a){var b={};
g.kc(a.I(),function(c){c.token?b[c.token]=c.id:this.me("Requesting availability of screen w/o lounge token.")});
return b},NTa=function(a){a=g.Ae(g.te(a.i,function(b){return b}));
g.fc(a);a.length?g.Sy("yt-remote-online-screen-ids",a.join(","),60):g.Uy("yt-remote-online-screen-ids")},g8=function(a,b){b=void 0===b?!1:b;
X7.call(this,"ScreenService");this.C=a;this.K=b;this.i=this.u=null;this.B=[];this.D={};PTa(this)},RTa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Ih(),l=c?$6(h,c):null;c&&(a.K||l)||(l=$6(h,b));if(l){l.uuid=b;var m=h8(a,l);d8(a.i,m,function(n){e(n?m:null)})}else c?QTa(a,c,(0,g.D)(function(n){var p=h8(this,new U6({name:d,
screenId:c,loungeToken:n,dialId:b||""}));d8(this.i,p,function(q){e(q?p:null)})},a),f):e(null)},STa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},TTa=function(a,b,c){d8(a.i,b,c)},QTa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Ht(Q7(a.C,"/pairing/get_lounge_token_batch"),e)},UTa=function(a){a.screens=a.u.Ih();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+X6(a.screens))},PTa=function(a){i8(a);
a.u=new $7(a.C);a.u.subscribe("screenChange",(0,g.D)(a.oS,a));UTa(a);a.K||(a.B=DSa(g.Ty("yt-remote-automatic-screen-cache")||[]));i8(a);a.info("Initializing automatic screens: "+X6(a.B));a.i=new c8(a.C,(0,g.D)(a.Ih,a,!0));a.i.subscribe("screenChange",(0,g.D)(function(){this.ea("onlineScreenChange")},a))},h8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=$6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),a.K||VTa(a));i8(a);a.D[b.uuid]=b.id;g.Sy("yt-remote-device-id-map",a.D,31536E3);return b},VTa=function(a){a=g.Jo(a.B,function(b){return"shortLived"!=b.idType});
g.Sy("yt-remote-automatic-screen-cache",g.tm(a,BSa))},i8=function(a){a.D=g.Ty("yt-remote-device-id-map")||{}},j8=function(a,b,c){g.ey.call(this);
this.Ba=c;this.B=a;this.i=b;this.C=null},k8=function(a,b){a.C=b;
a.ea("sessionScreen",a.C)},WTa=function(a,b){a.C&&(a.C.token=b,h8(a.B,a.C));
a.ea("sessionScreen",a.C)},l8=function(a,b){T7(a.Ba,b)},m8=function(a,b,c){j8.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.u=null;this.Z=(0,g.D)(this.wQ,this);this.Aa=(0,g.D)(this.wW,this);this.ma=g.zt(function(){XTa(d,null)},12E4);
this.K=this.D=this.I=this.S=0;this.va=!1;this.X="unknown"},n8=function(a,b){g.Bt(a.K);
a.K=0;0==b?YTa(a):a.K=g.zt(function(){YTa(a)},b)},YTa=function(a){ZTa(a,"getLoungeToken");
g.Bt(a.D);a.D=g.zt(function(){$Ta(a,null)},3E4)},ZTa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.bi(void 0));
var c={};c.type=b;a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ja,(0,g.D)(function(){l8(this,"Failed to send message: "+b+".")},a)):l8(a,"Sending yt message without session: "+g.bi(c))},o8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.uK(b,function(c){k8(a,c)},function(){return a.Ag()},5)):a.Ag(Error("Waiting for session status timed out."))},bUa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new U6(b);aUa(a,d,function(e){e?(a.va=!0,h8(a.B,d),k8(a,d),a.X="unknown",n8(a,c)):(g.Is(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.Ag())},5)},XTa=function(a,b){g.Bt(a.ma);
a.ma=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?bUa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Is(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),o8(a,b.screenId))):(g.Is(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),o8(a,b.screenId)):o8(a,b.screenId):a.Ag(Error("Waiting for session status timed out."))},$Ta=function(a,b){g.Bt(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.X=c,n8(a,3E4)):(WTa(a,b.loungeToken),a.va=!1,a.X="unknown",n8(a,b.loungeTokenRefreshIntervalMs))},aUa=function(a,b,c,d){g.Bt(a.I);
a.I=0;TTa(a.B,b,function(e){e||0>d?c(e):a.I=g.zt(function(){aUa(a,b,c,d-1)},300)})},cUa=function(a){g.Bt(a.S);
a.S=0;g.Bt(a.I);a.I=0;g.Bt(a.ma);a.ma=0;g.Bt(a.D);a.D=0;g.Bt(a.K);a.K=0},p8=function(a,b,c,d){j8.call(this,a,b,"DialSession");
this.config_=d;this.u=this.S=null;this.Aa="";this.Na=c;this.Ka=null;this.ma=g.Ja;this.X=NaN;this.Ia=(0,g.D)(this.xQ,this);this.D=g.Ja;this.K=this.I=0;this.Z=!1;this.va="unknown"},q8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.u)?0:b.getDialAppInfo))},dUa=function(a){a.D=a.B.eI(a.Aa,a.i.label,a.i.friendlyName,q8(a),function(b,c){a.D=g.Ja;
a.Z=!0;k8(a,b);"shortLived"==b.idType&&0<c&&r8(a,c)},function(b){a.D=g.Ja;
a.Ag(b)})},eUa=function(a){var b={};
b.pairingCode=a.Aa;b.theme=a.Na;OSa()&&(b.env_useStageMdx=1);return g.ui(b)},s8=function(a){return new Promise(function(b){a.Aa=Y6();
if(a.Ka){var c=new chrome.cast.DialLaunchResponse(!0,eUa(a));b(c);dUa(a)}else a.ma=function(){g.Bt(a.X);a.ma=function(){};
a.X=NaN;var d=new chrome.cast.DialLaunchResponse(!0,eUa(a));b(d);dUa(a)},a.X=g.zt(function(){a.ma()},100)})},gUa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new U6(b);return(new Promise(function(e){fUa(a,d,function(f){f?(a.Z=!0,h8(a.B,d),k8(a,d),r8(a,c)):g.Is(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):s8(a)})},hUa=function(a,b){var c=a.S.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){RTa(a.B,c,b,d,function(f){f&&f.token&&k8(a,f);e(f)},function(f){l8(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):s8(a)})},fUa=function(a,b,c,d){g.Bt(a.I);
a.I=0;TTa(a.B,b,function(e){e||0>d?c(e):a.I=g.zt(function(){fUa(a,b,c,d-1)},300)})},r8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
q8(a)&&(g.Bt(a.K),a.K=0,0==b?iUa(a):a.K=g.zt(function(){iUa(a)},b))},iUa=function(a){q8(a)&&a.u.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.va=c,r8(a,3E4)):(a.Z=!1,a.va="unknown",WTa(a,b.loungeToken),r8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.va="noLoungeTokenResponse";r8(a,3E4)})},jUa=function(a){g.Bt(a.I);
a.I=0;g.Bt(a.K);a.K=0;a.D();a.D=function(){};
g.Bt(a.X)},t8=function(a,b){j8.call(this,a,b,"ManualSession");
this.u=g.zt((0,g.D)(this.Js,this,null),150)},u8=function(a,b){g.ey.call(this);
this.config_=b;this.u=a;this.S=b.appId||"233637DE";this.C=b.theme||"cl";this.X=b.disableCastApi||!1;this.I=b.forceMirroring||!1;this.i=null;this.K=!1;this.B=[];this.D=(0,g.D)(this.pV,this)},kUa=function(a,b){return b?g.Mb(a.B,function(c){return V6(b,c.label)},a):null},v8=function(a){T7("Controller",a)},CTa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},w8=function(a){return a.K||!!a.B.length||!!a.i},x8=function(a,b,c){b!=a.i&&(g.he(a.i),(a.i=b)?(c?a.ea("yt-remote-cast2-receiver-resumed",
b.i):a.ea("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.D)(a.OM,a,b)),b.subscribe("sessionFailed",function(){return lUa(a,b)}),b.getScreen()?a.ea("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Js(null)):a.ea("yt-remote-cast2-session-change",null))},lUa=function(a,b){a.i==b&&a.ea("yt-remote-cast2-session-failed")},mUa=function(a){var b=a.u.dI(),c=a.i&&a.i.i;
a=g.tm(b,function(d){c&&V6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=kUa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},rUa=function(a,b,c,d){d.disableCastApi?y8("Cannot initialize because disabled by Mdx config."):nUa()?oUa(b,d)&&(z8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?pUa(a,c):(window.__onGCastApiAvailable=function(e,f){e?pUa(a,c):(A8("Failed to load cast API: "+f),B8(!1),z8(!1),g.Uy("yt-remote-cast-available"),g.Uy("yt-remote-cast-receiver"),
qUa(),c(!1))},d.loadCastApiSetupScript?g.Wy("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=g7()&&VSa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?i7():89<=g7()?XSa():(j7(),h7(WSa.map(SSa))))):y8("Cannot initialize because not running Chrome")},qUa=function(){y8("dispose");
var a=C8();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);sUa(!1);g.mv(D8);D8.length=0},E8=function(){return!!g.Ty("yt-remote-cast-installed")},tUa=function(){var a=g.Ty("yt-remote-cast-receiver");
return a?a.friendlyName:null},uUa=function(){y8("clearCurrentReceiver");
g.Uy("yt-remote-cast-receiver")},vUa=function(){return E8()?C8()?C8().getCastSession():(A8("getCastSelector: Cast is not initialized."),null):(A8("getCastSelector: Cast API is not installed!"),null)},G8=function(){E8()?C8()?F8()?(y8("Requesting cast selector."),C8().requestSession()):(y8("Wait for cast API to be ready to request the session."),D8.push(g.lv("yt-remote-cast2-api-ready",G8))):A8("requestCastSelector: Cast is not initialized."):A8("requestCastSelector: Cast API is not installed!")},H8=
function(a,b){F8()?C8().setConnectedScreenStatus(a,b):A8("setConnectedScreenStatus called before ready.")},nUa=function(){var a=0<=g.Ab.search(/ (CrMo|Chrome|CriOS)\//);
return g.Zi||a},wUa=function(a,b){C8().init(a,b)},oUa=function(a,b){var c=!1;
C8()||(a=new u8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Sy("yt-remote-cast-available",d);S6("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){y8("onReceiverSelected: "+d.friendlyName);
g.Sy("yt-remote-cast-receiver",d);S6("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){y8("onReceiverResumed: "+d.friendlyName);
g.Sy("yt-remote-cast-receiver",d);S6("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){y8("onSessionChange: "+W6(d));
d||g.Uy("yt-remote-cast-receiver");S6("yt-remote-cast2-session-change",d)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
y8("cloudview.createSingleton_: "+c);return c},C8=function(){return g.Ia("yt.mdx.remote.cloudview.instance_")},pUa=function(a,b){B8(!0);
z8(!1);wUa(a,function(c){c?(sUa(!0),g.nv("yt-remote-cast2-api-ready")):(A8("Failed to initialize cast API."),B8(!1),g.Uy("yt-remote-cast-available"),g.Uy("yt-remote-cast-receiver"),qUa());b(c)})},y8=function(a){T7("cloudview",a)},A8=function(a){T7("cloudview",a)},B8=function(a){y8("setCastInstalled_ "+a);
g.Sy("yt-remote-cast-installed",a)},F8=function(){return!!g.Ia("yt.mdx.remote.cloudview.apiReady_")},sUa=function(a){y8("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},z8=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},I8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.K=0;this.trackData=null;this.hasNext=this.Gk=!1;this.S=this.D=this.i=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},J8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Gk=!1;a.hasNext=!1;a.K=0;a.I=g.Ra();a.C=0;a.i=0;a.D=0;a.S=0;a.B=NaN;a.u=!1},K8=function(a){return a.Dc()?(g.Ra()-a.I)/1E3:0},L8=function(a,b){a.K=b;
a.I=g.Ra()},M8=function(a){switch(a.playerState){case 1:case 1081:return(g.Ra()-a.I)/1E3+a.K;
case -1E3:return 0}return a.K},N8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&J8(a)},O8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Le(a.trackData);b.hasPrevious=a.Gk;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.I;b.seekableStart=a.C;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.S;b.liveIngestionTime=a.B;return b},Q8=function(a,b){g.ey.call(this);
this.B=0;this.C=a;this.I=[];this.D=new yTa;this.u=this.i=null;this.X=(0,g.D)(this.XT,this);this.K=(0,g.D)(this.yw,this);this.S=(0,g.D)(this.VT,this);this.ma=(0,g.D)(this.fU,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.jG,this),xUa(this))):c=3;0!=c&&(b?this.jG(c):g.zt((0,g.D)(function(){this.jG(c)},this),0));
(a=vUa())&&P8(this,a);this.subscribe("yt-remote-cast2-session-change",this.ma)},R8=function(a){return new I8(a.C.getPlayerContextData())},xUa=function(a){g.kc("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled loopModeChange".split(" "),function(b){this.I.push(this.C.subscribe(b,g.Qa(this.nV,b),this))},a)},yUa=function(a){g.kc(a.I,function(b){this.C.unsubscribeByKey(b)},a);
a.I.length=0},S8=function(a){return 1==a.getState()},T8=function(a,b){var c=a.D;
50>c.i.length+c.u.length&&a.D.u.push(b)},V8=function(a,b,c){var d=R8(a);
L8(d,c);-1E3!=d.playerState&&(d.playerState=b);U8(a,d)},W8=function(a,b,c){a.C.sendMessage(b,c)},U8=function(a,b){yUa(a);
a.C.setPlayerContextData(O8(b));xUa(a)},P8=function(a,b){a.u&&(a.u.removeUpdateListener(a.X),a.u.removeMediaListener(a.K),a.yw(null));
a.u=b;a.u&&(T7("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.X),a.u.addMediaListener(a.K),a.u.media.length&&a.yw(a.u.media[0]))},zUa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=R8(a);b.contentId!=d.videoId&&T7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;L8(d,a.i.getEstimatedTime());U8(a,d)}else T7("CP","No cast media video. Ignoring state update.")},X8=function(a,b,c){return(0,g.D)(function(d){this.me("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.me("Retrying "+b+" using MDx browser channel."),W8(this,b,c))},a)},Y8=function(a,b,c,d){d=void 0===d?!1:d;
g.ey.call(this);this.D=NaN;this.va=!1;this.S=this.K=this.ma=this.Z=NaN;this.X=[];this.C=this.I=this.B=this.fc=this.i=null;this.Ia=a;this.Ba=d;this.X.push(g.Fu(window,"beforeunload",(0,g.D)(this.aS,this)));this.u=[];this.fc=new I8;this.Ka=b.id;this.Aa=b.idType;this.i=AUa(this,c);this.i.subscribe("handlerOpened",this.cU,this);this.i.subscribe("handlerClosed",this.ZT,this);this.i.subscribe("handlerError",this.aU,this);this.i.subscribe("handlerMessage",this.bU,this);this.i.TA(b.token);this.subscribe("remoteQueueChange",
function(){var e=this.fc.videoId;g.Vy()&&g.Sy("yt-remote-session-video-id",e)},this)},BUa=function(a){return g.Mb(a.u,function(b){return"LOUNGE_SCREEN"==b.type})},Z8=function(a){T7("conn",a)},AUa=function(a,b){return new M7(Q7(a.Ia,"/bc"),b,!1,function(){return a.iI()},"shortLived"==a.Aa)},$8=function(a,b){a.ea("proxyStateChange",b)},CUa=function(a){a.D=g.zt((0,g.D)(function(){Z8("Connecting timeout");
this.Ur(1)},a),2E4)},a9=function(a){g.Bt(a.D);
a.D=NaN},b9=function(a){g.Bt(a.Z);
a.Z=NaN},DUa=function(a){c9(a);
a.ma=g.zt((0,g.D)(function(){d9(this,"getNowPlaying")},a),2E4)},c9=function(a){g.Bt(a.ma);
a.ma=NaN},FUa=function(a,b){var c=null;
if(b){var d=BUa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Ha("yt.mdx.remote.remoteClient_",c,void 0);b&&(a9(a),b9(a));c=O7(a.i)&&isNaN(a.D);b==c?b&&($8(a,1),d9(a,"getSubtitlesTrack")):b?(a.tK()&&a.fc.reset(),$8(a,1),d9(a,"getNowPlaying"),EUa(a)):a.Ur(1)},GUa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.fc.videoId&&(g.Ge(b.params)?a.fc.trackData=null:a.fc.trackData=b.params,a.ea("remotePlayerChange"))},HUa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.fc.listId=b.params.listId||a.fc.listId;N8(a.fc,c,d);a.ea("remoteQueueChange")},JUa=function(a,b){b.params=b.params||{};
HUa(a,b);IUa(a,b);a.ea("autoplayDismissed")},IUa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
L8(a.fc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.fc.playerState&&(c=-1E3);a.fc.playerState=c;c=Number(b.params.loadedTime);a.fc.S=isNaN(c)?0:c;a.fc.Ij(Number(b.params.duration));c=a.fc;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.fc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.fc.playerState?DUa(a):c9(a);a.ea("remotePlayerChange")},KUa=function(a,b){if(-1E3!=a.fc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.fc.playerState=c;b=parseInt(b.params.currentTime,10);L8(a.fc,isNaN(b)?0:b);a.ea("remotePlayerChange")}},LUa=function(a,b){var c="true"==b.params.muted;
a.fc.volume=parseInt(b.params.volume,10);a.fc.muted=c;a.ea("remotePlayerChange")},MUa=function(a,b){a.I=b.params.videoId;
a.ea("nowAutoplaying",parseInt(b.params.timeout,10))},NUa=function(a,b){var c="true"==b.params.hasNext;
a.fc.Gk="true"==b.params.hasPrevious;a.fc.hasNext=c;a.ea("previousNextChange")},EUa=function(a){g.Bt(a.S);
a.S=g.zt((0,g.D)(a.Ur,a,1),864E5)},d9=function(a,b,c){c?Z8("Sending: action="+b+", params="+g.bi(c)):Z8("Sending: action="+b);
a.i.sendMessage(b,c)},e9=function(a){X7.call(this,"ScreenServiceProxy");
this.Te=a;this.i=[];this.i.push(this.Te.$_s("screenChange",(0,g.D)(this.BQ,this)));this.i.push(this.Te.$_s("onlineScreenChange",(0,g.D)(this.UU,this)))},RUa=function(a,b){NSa();
if(!f7||!f7.get("yt-remote-disable-remote-module-for-dev")){b=g.O("MDX_CONFIG")||b;FSa();d7();f9||(f9=new P7(b?b.loungeApiHost:void 0),OSa()&&(f9.i="/api/loungedev"));g9||(g9=g.Ia("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",g9,void 0));OUa();var c=h9();if(!c){var d=new g8(f9,b?b.disableAutomaticScreenCache||!1:!1);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=h9();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Ha("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);rUa(a,d,function(f){f?i9()&&H8(i9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){S6("yt-remote-receiver-availability-change")})},e)}b&&!g.Ia("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),j9("Initializing: "+
g.bi(b)),k9.push(g.lv("yt-remote-cast2-api-ready",function(){S6("yt-remote-api-ready")})),k9.push(g.lv("yt-remote-cast2-availability-change",function(){S6("yt-remote-receiver-availability-change")})),k9.push(g.lv("yt-remote-cast2-receiver-selected",function(){l9(null);
S6("yt-remote-auto-connect","cast-selector-receiver")})),k9.push(g.lv("yt-remote-cast2-receiver-resumed",function(){S6("yt-remote-receiver-resumed","cast-selector-receiver")})),k9.push(g.lv("yt-remote-cast2-session-change",PUa)),k9.push(g.lv("yt-remote-connection-change",function(f){f?H8(i9(),"YouTube TV"):m9()||(H8(null,null),uUa())})),k9.push(g.lv("yt-remote-cast2-session-failed",function(){S6("yt-remote-connection-failed")})),a=n9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.P("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),j9(" -- with channel params: "+g.bi(a)),a?(g.Sy("yt-remote-session-app",a.app),g.Sy("yt-remote-session-name",a.name)):(g.Uy("yt-remote-session-app"),g.Uy("yt-remote-session-name")),g.Ha("yt.mdx.remote.channelParams_",a,void 0),c.start(),i9()||QUa())}},SUa=function(){var a=h9().Te.$_gos();
var b=o9();b&&p9()&&(Z6(a,b)||a.push(b));return ESa(a)},q9=function(){var a=TUa();
!a&&E8()&&tUa()&&(a={key:"cast-selector-receiver",name:tUa()});return a},TUa=function(){var a=SUa(),b=o9();
b||(b=m9());return g.Mb(a,function(c){return b&&V6(b,c.key)?!0:!1})},o9=function(){var a=i9();
if(!a)return null;var b=h9().Ih();return $6(b,a)},PUa=function(a){j9("remote.onCastSessionChange_: "+W6(a));
if(a){var b=o9();if(b&&b.id==a.id){if(H8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))r9&&(r9.token=a),(b=p9())&&b.TA(a)}else b&&s9(),t9(a,1)}else p9()&&s9()},s9=function(){F8()?C8().stopSession():A8("stopSession called before API ready.");
var a=p9();a&&(a.disconnect(1),u9(null))},v9=function(){var a=p9();
return!!a&&3!=a.getProxyState()},j9=function(a){T7("remote",a)},h9=function(){if(!w9){var a=g.Ia("yt.mdx.remote.screenService_");
w9=a?new e9(a):null}return w9},i9=function(){return g.Ia("yt.mdx.remote.currentScreenId_")},UUa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},VUa=function(){return g.Ia("yt.mdx.remote.connectData_")},l9=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},p9=function(){return g.Ia("yt.mdx.remote.connection_")},u9=function(a){var b=p9();
l9(null);a||UUa("");g.Ha("yt.mdx.remote.connection_",a,void 0);g9&&(g.kc(g9,function(c){c(a)}),g9.length=0);
b&&!a?S6("yt-remote-connection-change",!1):!b&&a&&S6("yt-remote-connection-change",!0)},m9=function(){var a=g.Vy();
if(!a)return null;var b=h9();if(!b)return null;b=b.Ih();return $6(b,a)},t9=function(a,b){i9();
o9()&&o9();if(x9)r9=a;else{UUa(a.id);var c=g.Ia("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new Y8(f9,a,n9(),c);a.connect(b,VUa());a.subscribe("beforeDisconnect",function(d){S6("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){p9()&&(p9(),u9(null))});
a.subscribe("browserChannelAuthError",function(){var d=o9();d&&"shortLived"==d.idType&&(F8()?C8().handleBrowserChannelAuthError():A8("refreshLoungeToken called before API ready."))});
u9(a)}},QUa=function(){var a=m9();
a?(j9("Resume connection to: "+W6(a)),t9(a,0)):(e7(),uUa(),j9("Skipping connecting because no session screen found."))},OUa=function(){var a=n9();
if(g.Ge(a)){a=c7();var b=g.Ty("yt-remote-session-name")||"",c=g.Ty("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},n9=function(){return g.Ia("yt.mdx.remote.channelParams_")||{}},y9=function(a,b,c){g.H.call(this);
var d=this;this.u=a;this.J=b;this.Sb=c;this.events=new g.mD(this);this.ma=this.events.T(this.J,"onVolumeChange",function(e){WUa(d,e)});
this.D=!1;this.I=new g.MJ(64);this.i=new g.J(this.UN,500,this);this.B=new g.J(this.VN,1E3,this);this.S=new k7(this.LX,0,this);this.C={};this.X=new g.J(this.DO,1E3,this);this.K=new l7(this.seekTo,1E3,this);this.Z=g.Ja;g.I(this,this.events);this.events.T(b,"onCaptionsTrackListChanged",this.FU);this.events.T(b,"captionschanged",this.TT);this.events.T(b,"captionssettingschanged",this.bO);this.events.T(b,"videoplayerreset",this.mA);this.events.T(b,"mdxautoplaycancel",function(){d.Sb.QJ()});
a=this.Sb;a.isDisposed();a.subscribe("proxyStateChange",this.JM,this);a.subscribe("remotePlayerChange",this.Cw,this);a.subscribe("remoteQueueChange",this.mA,this);a.subscribe("previousNextChange",this.GM,this);a.subscribe("nowAutoplaying",this.AM,this);a.subscribe("autoplayDismissed",this.dM,this);g.I(this,this.i);g.I(this,this.B);g.I(this,this.S);g.I(this,this.X);g.I(this,this.K);this.bO();this.mA();this.Cw()},WUa=function(a,b){if(z9(a)){a.Sb.unsubscribe("remotePlayerChange",a.Cw,a);
var c=Math.round(b.volume);b=!!b.muted;var d=R8(a.Sb);if(c!==d.volume||b!==d.muted)a.Sb.setVolume(c,b),a.X.start();a.Sb.subscribe("remotePlayerChange",a.Cw,a)}},XUa=function(a){a.Wb(0);
a.i.stop();a.Tb(new g.MJ(64))},A9=function(a,b){if(z9(a)&&!a.D){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Ne(c,b));a.Sb.hI(a.J.getVideoData(1).videoId,c);a.C=R8(a.Sb).trackData}},B9=function(a,b){var c=a.J.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.Sb.playVideo(c.videoId,b,d,e,c.playerParams,c.Za,uSa(c));a.Tb(new g.MJ(1))},YUa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{RK:1});
c&&c.length?(a.J.setOption("captions","track",b),a.D=!1):(a.J.loadModule("captions"),a.D=!0)}else a.J.setOption("captions","track",{})},z9=function(a){return R8(a.Sb).videoId===a.J.getVideoData(1).videoId},C9=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",W:{role:"dialog"},U:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",U:[{G:"div",L:"ytp-mdx-popup-title",ya:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",ya:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",U:[{G:"button",Ga:["ytp-button","ytp-mdx-privacy-popup-cancel"],ya:"Cancel"},{G:"button",Ga:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],ya:"Confirm"}]}]}]});this.i=new g.rL(this,250);this.cancelButton=this.Fa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Fa("ytp-mdx-privacy-popup-confirm");g.I(this,this.i);this.T(this.cancelButton,"click",this.u);this.T(this.confirmButton,"click",this.B)},D9=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",U:[{G:"div",L:"ytp-remote-display-status",U:[{G:"div",L:"ytp-remote-display-status-icon",U:[g.gta()]},{G:"div",L:"ytp-remote-display-status-text",ya:"{{statustext}}"}]}]});this.api=a;this.i=new g.rL(this,250);g.I(this,this.i);this.T(a,"presentingplayerstatechange",this.onStateChange);ZUa(this,a.yb())},ZUa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.mI("Error on $RECEIVER_NAME",c):b.Dc()||g.U(b,4)?g.mI("Playing on $RECEIVER_NAME",c):g.mI("Connected to $RECEIVER_NAME",c);a.Sa("statustext",b);a.i.show()}else a.i.hide()},E9=function(a,b){g.LP.call(this,"Play on",0,a,b);
this.J=a;this.xo={};this.T(a,"onMdxReceiversChange",this.D);this.T(a,"presentingplayerstatechange",this.D);this.D()},F9=function(a){g.VM.call(this,a);
this.Nk={key:Y6(),name:"This computer"};this.gi=null;this.subscriptions=[];this.HF=this.Sb=null;this.xo=[this.Nk];this.Ym=this.Nk;this.xd=new g.MJ(64);this.uL=0;this.vf=-1;this.Lw=!1;this.Jw=this.Xs=null;if(!g.XE(this.player.V())&&!g.YE(this.player.V())){a=this.player;var b=g.yM(a);b&&(b=b.Cn())&&(b=new E9(a,b),g.I(this,b));b=new D9(a);g.I(this,b);g.IM(a,b.element,4);this.Xs=new C9;g.I(this,this.Xs);g.IM(a,this.Xs.element,4);this.Lw=!!m9()}},G9=function(a){a.Jw&&(a.player.removeEventListener("presentingplayerstatechange",
a.Jw),a.Jw=null)},$Ua=function(a,b,c){a.xd=c;
a.player.ea("presentingplayerstatechange",new g.ZH(c,b))},H9=function(a,b){if(b.key!==a.Ym.key)if(b.key===a.Nk.key)s9();
else{var c;(c=!a.player.V().N("mdx_enable_privacy_disclosure_ui"))||(c=((c=g.O("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.O("SESSION_INDEX")&&!g.O("LOGGED_IN")))||a.Lw||!a.Xs);(c?0:g.nF(a.player.V())||g.qF(a.player.V()))&&aVa(a);a.Ym=b;if(!a.player.V().N("disable_mdx_connection_in_mdx_module_for_music_web")||!g.YE(a.player.V())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&a.player.V().N("should_clear_video_data_on_player_cued_unstarted"))a=
null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=g.PM(f,l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Za,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=uSa(c))&&(a.locationInfo=c)}j9("Connecting to: "+g.bi(b));"cast-selector-receiver"==b.key?(l9(a||null),b=a||null,F8()?C8().setLaunchParams(b):A8("setLaunchParams called before ready.")):!a&&v9()&&
i9()==b.key?S6("yt-remote-connection-change",!0):(s9(),l9(a||null),a=h9().Ih(),(b=$6(a,b.key))&&t9(b,1))}}},aVa=function(a){a.player.yb().Dc()?a.player.pauseVideo():(a.Jw=function(b){!a.Lw&&g.aI(b,8)&&(a.player.pauseVideo(),G9(a))},a.player.addEventListener("presentingplayerstatechange",a.Jw));
a.Xs&&a.Xs.wd();p9()||(x9=!0)},cTa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},x7={"'":"\\'"},ASa={SY:"atp",P9:"ska",B8:"que",w6:"mus",O9:"sus",J2:"dsp",Y8:"seq",Z5:"mic",B1:"dpa",hZ:"cds",u6:"mlm",z1:"dsdtr"},f7,b7="",USa=PSa("loadCastFramework")||PSa("loadCastApplicationFramework"),WSa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(k7,g.H);g.k=k7.prototype;g.k.pQ=function(a){this.C=arguments;this.i=!1;this.Lb?this.B=g.Ra()+this.Uf:this.Lb=g.Ch(this.D,this.Uf)};
g.k.stop=function(){this.Lb&&(g.C.clearTimeout(this.Lb),this.Lb=null);this.B=null;this.i=!1;this.C=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.i&&(this.i=!1,this.I.apply(null,this.C)))};
g.k.xa=function(){this.stop();k7.le.xa.call(this)};
g.k.qQ=function(){this.Lb&&(g.C.clearTimeout(this.Lb),this.Lb=null);this.B?(this.Lb=g.Ch(this.D,this.B-g.Ra()),this.B=null):this.u?this.i=!0:(this.i=!1,this.I.apply(null,this.C))};g.v(l7,g.H);g.k=l7.prototype;g.k.cI=function(a){this.B=arguments;this.Lb||this.u?this.i=!0:m7(this)};
g.k.stop=function(){this.Lb&&(g.C.clearTimeout(this.Lb),this.Lb=null,this.i=!1,this.B=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.i||this.Lb||(this.i=!1,m7(this))};
g.k.xa=function(){g.H.prototype.xa.call(this);this.stop()};n7.prototype.stringify=function(a){return g.C.JSON.stringify(a,void 0)};
n7.prototype.parse=function(a){return g.C.JSON.parse(a,void 0)};var p7=new g.ef;g.v(YSa,g.ke);g.k=r7.prototype;g.k.Vo=null;g.k.Em=!1;g.k.Pt=null;g.k.cH=null;g.k.kt=null;g.k.Et=null;g.k.Sm=null;g.k.Bo=null;g.k.wq=null;g.k.Nf=null;g.k.uB=0;g.k.Nj=null;g.k.rB=null;g.k.Mm=null;g.k.vu=-1;g.k.IN=!0;g.k.pp=!1;g.k.hC=0;g.k.HA=null;var aTa={},u7={};g.k=r7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.rQ=function(a){a=a.target;var b=this.HA;b&&3==g.Ji(a)?b.cI():this.MO(a)};
g.k.MO=function(a){try{if(a==this.Nf)a:{var b=g.Ji(this.Nf),c=this.Nf.u,d=this.Nf.getStatus();if(g.yc&&!g.sc(10)||g.Jg&&!g.rc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Oi(this.Nf))break a;this.pp||4!=b||7==c||(8==c||0>=d?this.i.xj(3):this.i.xj(2));y7(this);var e=this.Nf.getStatus();this.vu=e;var f=g.Oi(this.Nf);if(this.Em=200==e){4==b&&v7(this);if(this.D){for(a=!0;!this.pp&&this.uB<f.length;){var h=bTa(this,f);if(h==u7){4==b&&(this.Mm=4,q7(15),a=!1);break}else if(h==aTa){this.Mm=4;q7(16);a=!1;
break}else z7(this,h)}4==b&&0==f.length&&(this.Mm=1,q7(17),a=!1);this.Em=this.Em&&a;a||(v7(this),w7(this))}else z7(this,f);this.Em&&!this.pp&&(4==b?this.i.Ux(this):(this.Em=!1,t7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.Mm=3,q7(13)):(this.Mm=0,q7(14)),v7(this),w7(this)}}catch(l){this.Nf&&g.Oi(this.Nf)}finally{}};
g.k.lW=function(a){o7((0,g.D)(this.kW,this,a),0)};
g.k.kW=function(a){this.pp||(y7(this),z7(this,a),t7(this))};
g.k.SM=function(a){o7((0,g.D)(this.jW,this,a),0)};
g.k.jW=function(a){this.pp||(v7(this),this.Em=a,this.i.Ux(this),this.i.xj(4))};
g.k.cancel=function(){this.pp=!0;v7(this)};
g.k.sW=function(){this.Pt=null;var a=Date.now();0<=a-this.cH?(2!=this.Et&&this.i.xj(3),v7(this),this.Mm=2,q7(18),w7(this)):eTa(this,this.cH-a)};
g.k.getLastError=function(){return this.Mm};g.k=hTa.prototype;g.k.iC=null;g.k.ph=null;g.k.IA=!1;g.k.WN=null;g.k.Ny=null;g.k.EE=null;g.k.jC=null;g.k.ai=null;g.k.ol=-1;g.k.wu=null;g.k.Mu=null;g.k.connect=function(a){this.jC=a;a=B7(this.i,null,this.jC);q7(3);this.WN=Date.now();var b=this.i.S;null!=b?(this.wu=b[0],(this.Mu=b[1])?(this.ai=1,iTa(this)):(this.ai=2,D7(this))):(P6(a,"MODE","init"),this.ph=new r7(this,void 0,void 0,void 0),this.ph.Vo=this.iC,s7(this.ph,a,!1,null,!0),this.ai=0)};
g.k.iR=function(a){if(a)this.ai=2,D7(this);else{q7(4);var b=this.i;b.Zj=b.Wm.ol;K7(b,9)}a&&this.xj(2)};
g.k.mD=function(a){return this.i.mD(a)};
g.k.abort=function(){this.ph&&(this.ph.cancel(),this.ph=null);this.ol=-1};
g.k.rf=function(){return!1};
g.k.KM=function(a,b){this.ol=a.vu;if(0==this.ai)if(b){try{var c=this.u.parse(b)}catch(d){a=this.i;a.Zj=this.ol;K7(a,2);return}this.wu=c[0];this.Mu=c[1]}else a=this.i,a.Zj=this.ol,K7(a,2);else if(2==this.ai)if(this.IA)q7(7),this.EE=Date.now();else if("11111"==b){if(q7(6),this.IA=!0,this.Ny=Date.now(),a=this.Ny-this.WN,!g.yc||g.sc(10)||500>a)this.ol=200,this.ph.cancel(),q7(12),C7(this.i,this,!0)}else q7(8),this.Ny=this.EE=Date.now(),this.IA=!1};
g.k.Ux=function(){this.ol=this.ph.vu;if(this.ph.Em)0==this.ai?this.Mu?(this.ai=1,iTa(this)):(this.ai=2,D7(this)):2==this.ai&&((!g.yc||g.sc(10)?!this.IA:200>this.EE-this.Ny)?(q7(11),C7(this.i,this,!1)):(q7(12),C7(this.i,this,!0)));else{0==this.ai?q7(9):2==this.ai&&q7(10);var a=this.i;this.ph.getLastError();a.Zj=this.ol;K7(a,2)}};
g.k.kx=function(){return this.i.kx()};
g.k.isActive=function(){return this.i.isActive()};
g.k.xj=function(a){this.i.xj(a)};g.k=E7.prototype;g.k.Yj=null;g.k.uv=null;g.k.Xg=null;g.k.Ke=null;g.k.kC=null;g.k.Oy=null;g.k.eJ=null;g.k.Vx=null;g.k.nw=0;g.k.nT=0;g.k.Of=null;g.k.qn=null;g.k.Cl=null;g.k.Ap=null;g.k.Wm=null;g.k.pB=null;g.k.Is=-1;g.k.tL=-1;g.k.Zj=-1;g.k.Yr=0;g.k.Ir=0;g.k.qp=8;g.Sa(kTa,g.ke);g.Sa(lTa,g.ke);g.k=E7.prototype;g.k.connect=function(a,b,c,d,e){q7(0);this.kC=b;this.uv=c||{};d&&void 0!==e&&(this.uv.OSID=d,this.uv.OAID=e);this.I?(o7((0,g.D)(this.AJ,this,a),100),pTa(this)):this.AJ(a)};
g.k.AJ=function(a){this.Wm=new hTa(this);this.Wm.iC=this.Yj;this.Wm.u=this.D;this.Wm.connect(a)};
g.k.rf=function(){return 0==this.i};
g.k.getState=function(){return this.i};
g.k.QM=function(a){this.qn=null;tTa(this,a)};
g.k.PM=function(){this.Cl=null;this.Ke=new r7(this,this.B,"rpc",this.K);this.Ke.Vo=this.Yj;this.Ke.hC=0;var a=this.eJ.clone();g.Yj(a,"RID","rpc");g.Yj(a,"SID",this.B);g.Yj(a,"CI",this.pB?"0":"1");g.Yj(a,"AID",this.Is);F7(this,a);if(!g.yc||g.sc(10))g.Yj(a,"TYPE","xmlhttp"),s7(this.Ke,a,!0,this.Vx,!1);else{g.Yj(a,"TYPE","html");var b=this.Ke,c=!!this.Vx;b.Et=3;b.Sm=O6(a.clone());dTa(b,c)}};
g.k.KM=function(a,b){if(0!=this.i&&(this.Ke==a||this.Xg==a))if(this.Zj=a.vu,this.Xg==a&&3==this.i)if(7<this.qp){try{var c=this.D.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.Cl){if(this.Ke)if(this.Ke.kt+3E3<this.Xg.kt)H7(this),this.Ke.cancel(),this.Ke=null;else break a;J7(this);q7(19)}}else this.tL=a[1],0<this.tL-this.Is&&37500>a[2]&&this.pB&&0==this.Ir&&!this.Ap&&(this.Ap=o7((0,g.D)(this.QT,this),6E3));else K7(this,11)}else null!=b&&K7(this,11);else if(this.Ke==
a&&H7(this),!g.jb(b))for(a=this.D.parse(b),b=0;b<a.length;b++)c=a[b],this.Is=c[0],c=c[1],2==this.i?"c"==c[0]?(this.B=c[1],this.Vx=c[2],c=c[3],null!=c?this.qp=c:this.qp=6,this.i=3,this.Of&&this.Of.wJ(),this.eJ=B7(this,this.kx()?this.Vx:null,this.kC),uTa(this)):"stop"==c[0]&&K7(this,7):3==this.i&&("stop"==c[0]?K7(this,7):"noop"!=c[0]&&this.Of&&this.Of.vJ(c),this.Ir=0)};
g.k.QT=function(){null!=this.Ap&&(this.Ap=null,this.Ke.cancel(),this.Ke=null,J7(this),q7(20))};
g.k.Ux=function(a){if(this.Ke==a){H7(this);this.Ke=null;var b=2}else if(this.Xg==a)this.Xg=null,b=1;else return;this.Zj=a.vu;if(0!=this.i)if(a.Em)if(1==b){b=Date.now()-a.kt;var c=p7;c.dispatchEvent(new kTa(c,a.wq?a.wq.length:0,b,this.Yr));G7(this);this.C.length=0}else uTa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.Zj)){if(d=1==b)this.Xg||this.qn||1==this.i||2<=this.Yr?d=!1:(this.qn=o7((0,g.D)(this.QM,this,a),vTa(this,this.Yr)),this.Yr++,d=!0);d=!(d||2==b&&J7(this))}if(d)switch(c){case 1:K7(this,
5);break;case 4:K7(this,10);break;case 3:K7(this,6);break;case 7:K7(this,12);break;default:K7(this,2)}}};
g.k.IR=function(a){if(!g.Pb(arguments,this.i))throw Error("Unexpected channel state: "+this.i);};
g.k.vX=function(a){a?q7(2):(q7(1),wTa(this,8))};
g.k.mD=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Di;a.S=!1;return a};
g.k.isActive=function(){return!!this.Of&&this.Of.isActive(this)};
g.k.xj=function(a){var b=p7;b.dispatchEvent(new lTa(b,a))};
g.k.kx=function(){return!(!g.yc||g.sc(10))};
g.k=xTa.prototype;g.k.wJ=function(){};
g.k.vJ=function(){};
g.k.uJ=function(){};
g.k.ZC=function(){};
g.k.gK=function(){return{}};
g.k.isActive=function(){return!0};g.k=yTa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.u.length};
g.k.clear=function(){this.i=[];this.u=[]};
g.k.contains=function(a){return g.Pb(this.i,a)||g.Pb(this.u,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.EMa)(b,a);0<=c?(g.Sb(b,c),b=!0):b=!1;return b||g.Tb(this.u,a)};
g.k.Op=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Sa(L7,g.H);g.k=L7.prototype;g.k.cW=function(){this.Uf=Math.min(3E5,2*this.Uf);this.B();this.u&&this.start()};
g.k.start=function(){var a=this.Uf+15E3*Math.random();g.Lq(this.i,a);this.u=Date.now()+a};
g.k.stop=function(){this.i.stop();this.u=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Uf=5E3};g.Sa(M7,xTa);g.k=M7.prototype;g.k.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.k.eg=function(a){return this.B.eg(a)};
g.k.ea=function(a,b){return this.B.ea.apply(this.B,arguments)};
g.k.dispose=function(){this.ma||(this.ma=!0,g.he(this.B),BTa(this),g.he(this.u),this.u=null,this.Z=function(){return""})};
g.k.isDisposed=function(){return this.ma};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.X="";this.u.stop();this.D=a||null;this.C=b||0;a=this.va+"/test";b=this.va+"/bind";var d=new E7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Aa),e=this.i;e&&(e.Of=null);d.Of=this;this.i=d;N7(this);if(this.i){d=g.O("ID_TOKEN");var f=this.i.Yj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Yj=f}e?(3!=e.getState()&&0==rTa(e)||e.getState(),this.i.connect(a,b,this.I,e.B,e.Is)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Ne(a,b);this.u.isActive()||2==(this.i?this.i.getState():0)?this.K.push(a):O7(this)&&(N7(this),qTa(this.i,a))};
g.k.wJ=function(){this.u.reset();this.D=null;this.C=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)qTa(this.i,a[b])}this.ea("handlerOpened")};
g.k.uJ=function(a){var b=2==a&&401==this.i.Zj;4==a||b||this.u.start();this.ea("handlerError",a,b)};
g.k.ZC=function(a){if(!this.u.isActive())this.ea("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.gK=function(){var a={v:2};this.X&&(a.gsessionid=this.X);0!=this.C&&(a.ui=""+this.C);0!=this.S&&(a.ui=""+this.S);this.D&&g.Ne(a,this.D);return a};
g.k.vJ=function(a){"S"==a[0]?this.X=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),oTa(this.i)):this.ea("handlerMessage",new zTa(a[0],a[1]))};
g.k.TA=function(a){(this.I.loungeIdToken=a)||this.u.stop();if(this.Ba&&this.i){var b=this.i.Yj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Yj=b}};
g.k.ZW=function(){this.u.isActive();0==rTa(this.i)&&this.connect(this.D,this.C)};P7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
P7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
P7.prototype.D=function(a){a(Error("request timed out"))};var ITa=Date.now(),S7=null,V7=Array(50),U7=-1,W7=!1;g.Sa(X7,g.ey);X7.prototype.Ih=function(){return this.screens};
X7.prototype.contains=function(a){return!!Z6(this.screens,a)};
X7.prototype.get=function(a){return a?$6(this.screens,a):null};
X7.prototype.info=function(a){T7(this.I,a)};g.v(Y7,g.ey);g.k=Y7.prototype;g.k.start=function(){!this.i&&isNaN(this.Lb)&&this.cN()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Lb)||(g.Bt(this.Lb),this.Lb=NaN)};
g.k.xa=function(){this.stop();g.ey.prototype.xa.call(this)};
g.k.cN=function(){this.Lb=NaN;this.i=g.Ht(Q7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.K},timeout:5E3,onSuccess:(0,g.D)(this.tQ,this),onError:(0,g.D)(this.sQ,this),onTimeout:(0,g.D)(this.uQ,this)})};
g.k.tQ=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.C;a.name=this.I;b=-1;this.D&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.ea("pairingComplete",new U6(a),b)};
g.k.sQ=function(a){this.i=null;a.status&&404==a.status?this.u>=bVa.length?this.ea("pairingFailed",Error("DIAL polling timed out")):(a=bVa[this.u],this.Lb=g.zt((0,g.D)(this.cN,this),a),this.u++):this.ea("pairingFailed",Error("Server error "+a.status))};
g.k.uQ=function(){this.i=null;this.ea("pairingFailed",Error("Server not responding"))};
var bVa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa($7,X7);g.k=$7.prototype;g.k.start=function(){Z7(this)&&this.ea("screenChange");!g.Ty("yt-remote-lounge-token-expiration")&&MTa(this);g.Bt(this.i);this.i=g.zt((0,g.D)(this.start,this),1E4)};
g.k.add=function(a,b){Z7(this);JTa(this,a);a8(this,!1);this.ea("screenChange");b(a);a.token||MTa(this)};
g.k.remove=function(a,b){var c=Z7(this);LTa(this,a)&&(a8(this,!1),c=!0);b(a);c&&this.ea("screenChange")};
g.k.nB=function(a,b,c,d){var e=Z7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,a8(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.ea("screenChange")};
g.k.xa=function(){g.Bt(this.i);$7.le.xa.call(this)};
g.k.fS=function(a){Z7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}a8(this,!b);b&&T7(this.I,"Missed "+b+" lounge tokens.")};
g.k.eS=function(a){T7(this.I,"Requesting lounge tokens failed: "+a)};g.v(c8,g.ey);g.k=c8.prototype;g.k.start=function(){var a=parseInt(g.Ty("yt-remote-fast-check-period")||"0",10);(this.C=g.Ra()-144E5<a?0:a)?f8(this):(this.C=g.Ra()+3E5,g.Sy("yt-remote-fast-check-period",this.C),this.SF())};
g.k.isEmpty=function(){return g.Ge(this.i)};
g.k.update=function(){b8("Updating availability on schedule.");var a=this.I(),b=g.te(this.i,function(c,d){return c&&!!$6(a,d)},this);
e8(this,b)};
g.k.xa=function(){g.Bt(this.B);this.B=NaN;this.u&&(this.u.abort(),this.u=null);g.ey.prototype.xa.call(this)};
g.k.SF=function(){g.Bt(this.B);this.B=NaN;this.u&&this.u.abort();var a=OTa(this);if(Q6(a)){var b=Q7(this.D,"/pairing/get_screen_availability");this.u=R7(this.D,b,{lounge_token:g.Ae(a).join(",")},(0,g.D)(this.JV,this,a),(0,g.D)(this.IV,this))}else e8(this,{}),f8(this)};
g.k.JV=function(a,b){this.u=null;var c=g.Ae(OTa(this));if(g.gc(c,g.Ae(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;e8(this,c);f8(this)}else this.me("Changing Screen set during request."),this.SF()};
g.k.IV=function(a){this.me("Screen availability failed: "+a);this.u=null;f8(this)};
g.k.me=function(a){T7("OnlineScreenService",a)};g.Sa(g8,X7);g.k=g8.prototype;g.k.start=function(){this.u.start();this.i.start();this.screens.length&&(this.ea("screenChange"),this.i.isEmpty()||this.ea("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.i.update()};
g.k.nB=function(a,b,c,d){this.u.contains(a)?this.u.nB(a,b,c,d):(a="Updating name of unknown screen: "+a.name,T7(this.I,a),d(Error(a)))};
g.k.Ih=function(a){return a?this.screens:g.Vb(this.screens,g.Jo(this.B,function(b){return!this.contains(b)},this))};
g.k.dI=function(){return g.Jo(this.Ih(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.eI=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new Y7(this.C,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.he(l);e(h8(h,m),n)});
l.subscribe("pairingFailed",function(m){g.he(l);f(m)});
l.start();return(0,g.D)(l.stop,l)};
g.k.vQ=function(a,b,c,d){g.Ht(Q7(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.D)(function(e,f){e=new U6(f.screen||{});if(!e.name||STa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);STa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(h8(this,e))},this),
onError:(0,g.D)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.D)(function(){d(Error("pairing request timed out."))},this)})};
g.k.xa=function(){g.he(this.u);g.he(this.i);g8.le.xa.call(this)};
g.k.oS=function(){UTa(this);this.ea("screenChange");this.i.update()};
g8.prototype.dispose=g8.prototype.dispose;g.Sa(j8,g.ey);g.k=j8.prototype;g.k.getScreen=function(){return this.C};
g.k.Ag=function(a){this.isDisposed()||(a&&(l8(this,""+a),this.ea("sessionFailed")),this.C=null,this.ea("sessionScreen",null))};
g.k.info=function(a){T7(this.Ba,a)};
g.k.fI=function(){return null};
g.k.iG=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.D)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.D)(function(){l8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.xa=function(){this.iG("");j8.le.xa.call(this)};g.v(m8,j8);g.k=m8.prototype;g.k.hG=function(a){if(this.u){if(this.u==a)return;l8(this,"Overriding cast session with new session object");cUa(this);this.va=!1;this.X="unknown";this.u.removeUpdateListener(this.Z);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa)}this.u=a;this.u.addUpdateListener(this.Z);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa);ZTa(this,"getMdxSessionStatus")};
g.k.Js=function(a){this.info("launchWithParams no-op for Cast: "+g.bi(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.D)(function(){this.Ag()},this),(0,g.D)(function(){this.Ag(Error("Failed to stop receiver app."))},this)):this.Ag(Error("Stopping cast device without session."))};
g.k.iG=function(){};
g.k.xa=function(){this.info("disposeInternal");cUa(this);this.u&&(this.u.removeUpdateListener(this.Z),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa));this.u=null;j8.prototype.xa.call(this)};
g.k.wW=function(a,b){if(!this.isDisposed())if(b)if(b=R6(b),g.Na(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.bi(b)),a){case "mdxSessionStatus":XTa(this,b);break;case "loungeToken":$Ta(this,b);break;default:l8(this,"Unknown youtube message: "+a)}else l8(this,"Unable to parse message.");else l8(this,"No data in message.")};
g.k.uK=function(a,b,c,d){g.Bt(this.S);this.S=0;RTa(this.B,this.i.label,a,this.i.friendlyName,(0,g.D)(function(e){e?b(e):0<=d?(l8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.S=g.zt((0,g.D)(this.uK,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.fI=function(){return this.u};
g.k.wQ=function(a){this.isDisposed()||a||(l8(this,"Cast session died."),this.Ag())};g.v(p8,j8);g.k=p8.prototype;g.k.hG=function(a){this.u=a;this.u.addUpdateListener(this.Ia)};
g.k.Js=function(a){this.Ka=a;this.ma()};
g.k.stop=function(){jUa(this);this.u?this.u.stop((0,g.D)(this.Ag,this,null),(0,g.D)(this.Ag,this,"Failed to stop DIAL device.")):this.Ag()};
g.k.xa=function(){jUa(this);this.u&&this.u.removeUpdateListener(this.Ia);this.u=null;j8.prototype.xa.call(this)};
g.k.xQ=function(a){this.isDisposed()||a||(l8(this,"DIAL session died."),this.D(),this.D=g.Ja,this.Ag())};g.v(t8,j8);t8.prototype.stop=function(){this.Ag()};
t8.prototype.hG=function(){};
t8.prototype.Js=function(){g.Bt(this.u);this.u=NaN;var a=$6(this.B.Ih(),this.i.label);a?k8(this,a):this.Ag(Error("No such screen"))};
t8.prototype.xa=function(){g.Bt(this.u);this.u=NaN;j8.prototype.xa.call(this)};g.v(u8,g.ey);g.k=u8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.S,[chrome.cast.Capability.AUDIO_OUT]);this.X||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.I?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.D)(this.sV,this);c=new chrome.cast.ApiConfig(c,(0,g.D)(this.LM,this),e,d,a);c.customDialLaunchCallback=(0,g.D)(this.nU,this);
chrome.cast.initialize(c,(0,g.D)(function(){this.isDisposed()||(chrome.cast.addReceiverActionListener(this.D),FTa(),this.u.subscribe("onlineScreenChange",(0,g.D)(this.gI,this)),this.B=mUa(this),chrome.cast.setCustomReceivers(this.B,g.Ja,(0,g.D)(function(f){this.me("Failed to set initial custom receivers: "+g.bi(f))},this)),this.ea("yt-remote-cast2-availability-change",w8(this)),b(!0))},this),(0,g.D)(function(f){this.me("Failed to initialize API: "+g.bi(f));
b(!1)},this))};
g.k.eX=function(a,b){v8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)v8("Unsetting old screen status: "+this.i.i.friendlyName),x8(this,null)}if(a&&b){if(!this.i){c=$6(this.u.Ih(),a);if(!c){v8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){v8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=kUa(this,c);a||(v8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(a),chrome.cast.setCustomReceivers(this.B,g.Ja,(0,g.D)(function(d){this.me("Failed to set initial custom receivers: "+g.bi(d))},this)));
v8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);x8(this,new t8(this.u,a),!0)}this.i.iG(b)}else v8("setConnectedScreenStatus: no screen.")};
g.k.fX=function(a){this.isDisposed()?this.me("Setting connection data on disposed cast v2"):this.i?this.i.Js(a):this.me("Setting connection data without a session")};
g.k.zQ=function(){this.isDisposed()?this.me("Stopping session on disposed cast v2"):this.i?(this.i.stop(),x8(this,null)):v8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.D)(this.LM,this),(0,g.D)(this.MV,this))};
g.k.xa=function(){this.u.unsubscribe("onlineScreenChange",(0,g.D)(this.gI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=CTa,b=g.Ia("yt.mdx.remote.debug.handlers_");g.Tb(b||[],a);g.he(this.i);g.ey.prototype.xa.call(this)};
g.k.me=function(a){T7("Controller",a)};
g.k.OM=function(a,b){this.i==a&&(b||x8(this,null),this.ea("yt-remote-cast2-session-change",b))};
g.k.pV=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),v8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)v8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{v8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.ea("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:x8(this,
new t8(this.u,a));break;case chrome.cast.ReceiverType.DIAL:x8(this,new p8(this.u,a,this.C,this.config_));break;case chrome.cast.ReceiverType.CAST:x8(this,new m8(this.u,a,this.config_));break;default:this.me("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.me("Stopping receiver w/o session: "+a.friendlyName)}else this.me("onReceiverAction_ called without receiver.")};
g.k.nU=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.me("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.me("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return v8("Reselecting dial screen."),
this.ea("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.me('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);x8(this,new p8(this.u,b,this.C,this.config_))}b=this.i;b.S=a;b.S.appState==chrome.cast.DialAppState.RUNNING?(a=b.S.extraData||{},c=a.screenId||null,q8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=gUa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.S.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.Is(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=hUa(b,c)):a=hUa(b,c)):a=s8(b);return a};
g.k.LM=function(a){var b=this;if(!this.isDisposed()&&!this.I){v8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)v8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),x8(this,new m8(this.u,c,this.config_),!0);else{this.me("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=$6(this.u.Ih(),
d.label);e&&V6(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(v8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.he(this.i),this.i=new m8(this.u,c,this.config_),this.i.subscribe("sessionScreen",(0,g.D)(this.OM,this,this.i)),this.i.subscribe("sessionFailed",function(){return lUa(b,b.i)}),this.i.Js(null));
this.i.hG(a)}}};
g.k.yQ=function(){return this.i?this.i.fI():null};
g.k.MV=function(a){this.isDisposed()||(this.me("Failed to estabilish a session: "+g.bi(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&x8(this,null),this.ea("yt-remote-cast2-session-failed"))};
g.k.sV=function(a){v8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=w8(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;w8(this)!=b&&this.ea("yt-remote-cast2-availability-change",w8(this))}};
g.k.gI=function(){this.isDisposed()||(this.B=mUa(this),v8("Updating custom receivers: "+g.bi(this.B)),chrome.cast.setCustomReceivers(this.B,g.Ja,(0,g.D)(function(){this.me("Failed to set custom receivers.")},this)),this.ea("yt-remote-cast2-availability-change",w8(this)))};
u8.prototype.setLaunchParams=u8.prototype.fX;u8.prototype.setConnectedScreenStatus=u8.prototype.eX;u8.prototype.stopSession=u8.prototype.zQ;u8.prototype.getCastSession=u8.prototype.yQ;u8.prototype.requestSession=u8.prototype.requestSession;u8.prototype.init=u8.prototype.init;u8.prototype.dispose=u8.prototype.dispose;var D8=[];g.k=I8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";J8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Gk=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.I=a.playerTimeAt,this.C=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.S=a.loadedTime,this.B=a.liveIngestionTime,this.u=
!isNaN(this.B))};
g.k.Dc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.Ij=function(a){this.D=isNaN(a)?0:a};
g.k.getDuration=function(){return this.u?this.D+K8(this):this.D};
g.k.clone=function(){return new I8(O8(this))};g.v(Q8,g.ey);g.k=Q8.prototype;g.k.getState=function(){return this.B};
g.k.play=function(){S8(this)?(this.i?this.i.play(null,g.Ja,X8(this,"play")):W8(this,"play"),V8(this,1,M8(R8(this))),this.ea("remotePlayerChange")):T8(this,this.play)};
g.k.pause=function(){S8(this)?(this.i?this.i.pause(null,g.Ja,X8(this,"pause")):W8(this,"pause"),V8(this,2,M8(R8(this))),this.ea("remotePlayerChange")):T8(this,this.pause)};
g.k.seekTo=function(a){if(S8(this)){if(this.i){var b=R8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Dc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,X8(this,"seekTo",{newTime:a}))}else W8(this,"seekTo",{newTime:a});V8(this,3,a);this.ea("remotePlayerChange")}else T8(this,g.Qa(this.seekTo,a))};
g.k.stop=function(){if(S8(this)){this.i?this.i.stop(null,g.Ja,X8(this,"stopVideo")):W8(this,"stopVideo");var a=R8(this);a.index=-1;a.videoId="";J8(a);U8(this,a);this.ea("remotePlayerChange")}else T8(this,this.stop)};
g.k.setVolume=function(a,b){if(S8(this)){var c=R8(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.D)(function(){T7("CP","set receiver volume: "+d)},this),(0,g.D)(function(){this.me("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.D)(function(){T7("CP","set receiver muted: "+b)},this),(0,g.D)(function(){this.me("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);W8(this,"setVolume",e)}c.muted=b;c.volume=a;U8(this,c)}else T8(this,g.Qa(this.setVolume,a,b))};
g.k.hI=function(a,b){if(S8(this)){var c=R8(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.bi(b.style),g.Ne(a,c.trackData));W8(this,"setSubtitlesTrack",a);U8(this,c)}else T8(this,g.Qa(this.hI,a,b))};
g.k.setAudioTrack=function(a,b){S8(this)?(b=b.getLanguageInfo().getId(),W8(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=R8(this),a.audioTrackId=b,U8(this,a)):T8(this,g.Qa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=R8(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);N8(l,a,c||0);void 0!==b&&(L8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.bi(h));W8(this,"setPlaylist",m);d||U8(this,l)};
g.k.AA=function(a,b){if(S8(this)){if(a&&b){var c=R8(this);N8(c,a,b);U8(this,c)}W8(this,"previous")}else T8(this,g.Qa(this.AA,a,b))};
g.k.nextVideo=function(a,b){if(S8(this)){if(a&&b){var c=R8(this);N8(c,a,b);U8(this,c)}W8(this,"next")}else T8(this,g.Qa(this.nextVideo,a,b))};
g.k.Lr=function(){if(S8(this)){W8(this,"clearPlaylist");var a=R8(this);a.reset();U8(this,a);this.ea("remotePlayerChange")}else T8(this,this.Lr)};
g.k.QJ=function(){S8(this)?W8(this,"dismissAutoplay"):T8(this,this.QJ)};
g.k.dispose=function(){if(3!=this.B){var a=this.B;this.B=3;this.ea("proxyStateChange",a,this.B)}g.ey.prototype.dispose.call(this)};
g.k.xa=function(){yUa(this);this.C=null;this.D.clear();P8(this,null);g.ey.prototype.xa.call(this)};
g.k.jG=function(a){if((a!=this.B||2==a)&&3!=this.B&&0!=a){var b=this.B;this.B=a;this.ea("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,0===b.i.length&&(b.i=b.u,b.i.reverse(),b.u=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.nV=function(a,b){this.ea(a,b)};
g.k.XT=function(a){if(!a)this.yw(null),P8(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=R8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)T7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,U8(this,b)}};
g.k.yw=function(a){T7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.S);if(this.i=a)this.i.addUpdateListener(this.S),zUa(this),this.ea("remotePlayerChange")};
g.k.VT=function(a){a?(zUa(this),this.ea("remotePlayerChange")):this.yw(null)};
g.k.EG=function(){W8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.fU=function(){var a=vUa();a&&P8(this,a)};
g.k.me=function(a){T7("CP",a)};g.v(Y8,g.ey);g.k=Y8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Ba&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.fc.listId=c);this.fc.videoId=d;this.fc.index=l||0;this.fc.state=3;L8(this.fc,
n);this.C="UNSUPPORTED";c=this.Ba?"setInitialState":"setPlaylist";Z8("Connecting with "+c+" and params: "+g.bi(m));this.i.connect({method:c,params:g.bi(m)},a,ISa())}else Z8("Connecting without params"),this.i.connect({},a,ISa());CUa(this)};
g.k.TA=function(a){this.i.TA(a)};
g.k.dispose=function(){this.isDisposed()||(g.Ha("yt.mdx.remote.remoteClient_",null,void 0),this.ea("beforeDispose"),$8(this,3));g.ey.prototype.dispose.call(this)};
g.k.xa=function(){a9(this);c9(this);b9(this);g.Bt(this.K);this.K=NaN;g.Bt(this.S);this.S=NaN;this.B=null;g.Gu(this.X);this.X.length=0;this.i.dispose();g.ey.prototype.xa.call(this);this.C=this.I=this.u=this.fc=this.i=null};
g.k.aS=function(){this.Ur(2)};
g.k.cU=function(){Z8("Channel opened");this.va&&(this.va=!1,b9(this),this.Z=g.zt((0,g.D)(function(){Z8("Timing out waiting for a screen.");this.Ur(1)},this),15E3));
MSa(ATa(this.i),this.Ka)};
g.k.ZT=function(){Z8("Channel closed");isNaN(this.D)?e7(!0):e7();this.dispose()};
g.k.aU=function(a,b){e7();isNaN(this.Kv())?(b&&"shortLived"==this.Aa&&this.ea("browserChannelAuthError",a),Z8("Channel error: "+a+" without reconnection"),this.dispose()):(this.va=!0,Z8("Channel error: "+a+" with reconnection in "+this.Kv()+" ms"),$8(this,2))};
g.k.eL=function(a){if(!this.u||0===this.u.length)return!1;for(var b=g.t(this.u),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.bU=function(a){a.params?Z8("Received: action="+a.action+", params="+g.bi(a.params)):Z8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=R6(a.params.devices);this.u=g.tm(a,function(c){return new T6(c)});
a=!!g.Mb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
FUa(this,a);a=this.eL("mlm");this.ea("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.Ub(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
FUa(this,!1);break;case "remoteConnected":var b=new T6(R6(a.params.device));g.Mb(this.u,function(c){return b?c.id==b.id:!1})||vSa(this.u,b);
break;case "remoteDisconnected":b=new T6(R6(a.params.device));g.Ub(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":HUa(this,a);break;case "nowPlaying":JUa(this,a);break;case "onStateChange":IUa(this,a);break;case "onAdStateChange":KUa(this,a);break;case "onVolumeChanged":LUa(this,a);break;case "onSubtitlesTrackChanged":GUa(this,a);break;case "nowAutoplaying":MUa(this,a);break;case "autoplayDismissed":this.ea("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.ea("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.ea("autoplayModeChange",this.C);"DISABLED"==this.C&&this.ea("autoplayDismissed");break;case "onHasPreviousNextChanged":NUa(this,a);break;case "requestAssistedSignIn":this.ea("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.ea("loopModeChange",a.params.loopMode);break;default:Z8("Unrecognized action: "+a.action)}};
g.k.SW=function(){if(this.B){var a=this.B;this.B=null;this.fc.videoId!=a&&d9(this,"getNowPlaying")}};
g.k.WR=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.Kv())?O7(this.i)&&isNaN(this.D)&&(a=1):a=2);return a};
g.k.Ur=function(a){Z8("Disconnecting with "+a);g.Ha("yt.mdx.remote.remoteClient_",null,void 0);a9(this);this.ea("beforeDisconnect",a);1==a&&e7();BTa(this.i,a);this.dispose()};
g.k.UR=function(){var a=this.fc;this.B&&(a=this.fc.clone(),N8(a,this.B,a.index));return O8(a)};
g.k.gX=function(a){var b=new I8(a);b.videoId&&b.videoId!=this.fc.videoId&&(this.B=b.videoId,g.Bt(this.K),this.K=g.zt((0,g.D)(this.SW,this),5E3));var c=[];this.fc.listId==b.listId&&this.fc.videoId==b.videoId&&this.fc.index==b.index||c.push("remoteQueueChange");this.fc.playerState==b.playerState&&this.fc.volume==b.volume&&this.fc.muted==b.muted&&M8(this.fc)==M8(b)&&g.bi(this.fc.trackData)==g.bi(b.trackData)||c.push("remotePlayerChange");this.fc.reset(a);g.kc(c,function(d){this.ea(d)},this)};
g.k.tK=function(){var a=this.i.I.id,b=g.Mb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Kv=function(){var a=this.i;return a.u.isActive()?a.u.u-Date.now():NaN};
g.k.RR=function(){return this.C||"UNSUPPORTED"};
g.k.SR=function(){return this.I||""};
g.k.AQ=function(){if(!isNaN(this.Kv())){var a=this.i.u;g.Mq(a.i);a.start()}};
g.k.dX=function(a,b){d9(this,a,b);EUa(this)};
g.k.iI=function(){var a=g.Tt("SID","")||"",b=g.Tt("SAPISID","")||"",c=g.Tt("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.vc(g.eb(a),2);b=g.vc(g.eb(b),2);c=g.vc(g.eb(c),2);return g.vc(g.eb(a+","+b+","+c),2)};
Y8.prototype.subscribe=Y8.prototype.subscribe;Y8.prototype.unsubscribeByKey=Y8.prototype.eg;Y8.prototype.getProxyState=Y8.prototype.WR;Y8.prototype.disconnect=Y8.prototype.Ur;Y8.prototype.getPlayerContextData=Y8.prototype.UR;Y8.prototype.setPlayerContextData=Y8.prototype.gX;Y8.prototype.getOtherConnectedRemoteId=Y8.prototype.tK;Y8.prototype.getReconnectTimeout=Y8.prototype.Kv;Y8.prototype.getAutoplayMode=Y8.prototype.RR;Y8.prototype.getAutoplayVideoId=Y8.prototype.SR;Y8.prototype.reconnect=Y8.prototype.AQ;
Y8.prototype.sendMessage=Y8.prototype.dX;Y8.prototype.getXsrfToken=Y8.prototype.iI;Y8.prototype.isCapabilitySupportedOnConnectedDevices=Y8.prototype.eL;g.v(e9,X7);g.k=e9.prototype;g.k.Ih=function(a){return this.Te.$_gs(a)};
g.k.contains=function(a){return!!this.Te.$_c(a)};
g.k.get=function(a){return this.Te.$_g(a)};
g.k.start=function(){this.Te.$_st()};
g.k.add=function(a,b,c){this.Te.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Te.$_r(a,b,c)};
g.k.nB=function(a,b,c,d){this.Te.$_un(a,b,c,d)};
g.k.xa=function(){for(var a=0,b=this.i.length;a<b;++a)this.Te.$_ubk(this.i[a]);this.i.length=0;this.Te=null;X7.prototype.xa.call(this)};
g.k.BQ=function(){this.ea("screenChange")};
g.k.UU=function(){this.ea("onlineScreenChange")};
g8.prototype.$_st=g8.prototype.start;g8.prototype.$_gspc=g8.prototype.vQ;g8.prototype.$_gsppc=g8.prototype.eI;g8.prototype.$_c=g8.prototype.contains;g8.prototype.$_g=g8.prototype.get;g8.prototype.$_a=g8.prototype.add;g8.prototype.$_un=g8.prototype.nB;g8.prototype.$_r=g8.prototype.remove;g8.prototype.$_gs=g8.prototype.Ih;g8.prototype.$_gos=g8.prototype.dI;g8.prototype.$_s=g8.prototype.subscribe;g8.prototype.$_ubk=g8.prototype.eg;var r9=null,x9=!1,f9=null,g9=null,w9=null,k9=[];g.v(y9,g.H);g.k=y9.prototype;g.k.xa=function(){g.H.prototype.xa.call(this);this.i.stop();this.B.stop();this.S.stop();this.Z();var a=this.Sb;a.unsubscribe("proxyStateChange",this.JM,this);a.unsubscribe("remotePlayerChange",this.Cw,this);a.unsubscribe("remoteQueueChange",this.mA,this);a.unsubscribe("previousNextChange",this.GM,this);a.unsubscribe("nowAutoplaying",this.AM,this);a.unsubscribe("autoplayDismissed",this.dM,this);this.Sb=this.u=null};
g.k.nj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Sb.B)if(z9(this)){if(!R8(this.Sb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":R8(this.Sb).Dc()?this.Sb.pause():this.Sb.play();break;case "control_play":this.Sb.play();break;case "control_pause":this.Sb.pause();break;case "control_seek":this.K.cI(c[0],c[1]);break;case "control_subtitles_set_track":A9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();B9(this,0===c?void 0:c);break;case "control_seek":B9(this,c[0]);break;case "control_subtitles_set_track":A9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.TT=function(a){this.S.pQ(a)};
g.k.LX=function(a){this.nj("control_subtitles_set_track",g.Ge(a)?null:a)};
g.k.bO=function(){var a=this.J.getOption("captions","track");g.Ge(a)||A9(this,a)};
g.k.Wb=function(a){this.u.Wb(a,this.J.getVideoData().lengthSeconds)};
g.k.FU=function(){g.Ge(this.C)||YUa(this,this.C);this.D=!1};
g.k.JM=function(a,b){this.B.stop();2===b&&this.VN()};
g.k.Cw=function(){if(z9(this)){this.i.stop();var a=R8(this.Sb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.vf=1;break;case 1082:case 1083:this.u.vf=0;break;default:this.u.vf=-1}switch(a.playerState){case 1081:case 1:this.Tb(new g.MJ(8));this.UN();break;case 1085:case 3:this.Tb(new g.MJ(9));break;case 1083:case 0:this.Tb(new g.MJ(2));this.K.stop();this.Wb(this.J.getVideoData().lengthSeconds);break;case 1084:this.Tb(new g.MJ(4));break;case 2:this.Tb(new g.MJ(4));this.Wb(M8(a));
break;case -1:this.Tb(new g.MJ(64));break;case -1E3:this.Tb(new g.MJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=R8(this.Sb).trackData;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,YUa(this,a));a=R8(this.Sb);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.X.isActive()||this.DO()}else XUa(this)};
g.k.GM=function(){this.J.ea("mdxpreviousnextchange")};
g.k.mA=function(){z9(this)||XUa(this)};
g.k.AM=function(a){isNaN(a)||this.J.ea("mdxnowautoplaying",a)};
g.k.dM=function(){this.J.ea("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){z9(this)&&this.Sb.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===R8(this.Sb).playerState?B9(this,a):b&&this.Sb.seekTo(a)};
g.k.DO=function(){var a=this;if(z9(this)){var b=R8(this.Sb);this.events.hc(this.ma);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.ma=this.events.T(this.J,"onVolumeChange",function(c){WUa(a,c)})}};
g.k.UN=function(){this.i.stop();if(!this.Sb.isDisposed()){var a=R8(this.Sb);a.Dc()&&this.Tb(new g.MJ(8));this.Wb(M8(a));this.i.start()}};
g.k.VN=function(){this.B.stop();this.i.stop();var a=this.Sb.C.getReconnectTimeout();2==this.Sb.B&&!isNaN(a)&&this.B.start()};
g.k.Tb=function(a){this.B.stop();var b=this.I;if(!g.RJ(b,a)){var c=g.U(a,2);c!==g.U(this.I,2)&&this.J.vt(c);this.I=a;$Ua(this.u,b,a)}};g.v(C9,g.V);C9.prototype.wd=function(){this.i.show()};
C9.prototype.Eb=function(){this.i.hide()};
C9.prototype.u=function(){S6("mdx-privacy-popup-cancel");this.Eb()};
C9.prototype.B=function(){S6("mdx-privacy-popup-confirm");this.Eb()};g.v(D9,g.V);D9.prototype.onStateChange=function(a){ZUa(this,a.state)};g.v(E9,g.LP);E9.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.xo=g.lc(a,this.i,this),g.MP(this,g.tm(a,this.i)),a=this.J.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Zh(a),this.enable(!0)):this.enable(!1)};
E9.prototype.i=function(a){return a.key};
E9.prototype.ej=function(a){return"cast-selector-receiver"===a?"Cast...":this.xo[a].name};
E9.prototype.Cf=function(a){g.LP.prototype.Cf.call(this,a);this.J.setOption("remote","currentReceiver",this.xo[a]);this.Ab.Eb()};g.v(F9,g.VM);g.k=F9.prototype;
g.k.create=function(){var a=this.player.V(),b=g.VE(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:a.N("mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:a.N("enable_dial_short_lived_lounge_token"),enableCastLoungeToken:a.N("enable_cast_short_lived_lounge_token")};RUa(b,a);this.subscriptions.push(g.lv("yt-remote-before-disconnect",this.ST,this));this.subscriptions.push(g.lv("yt-remote-connection-change",this.tV,this));this.subscriptions.push(g.lv("yt-remote-receiver-availability-change",this.IM,
this));this.subscriptions.push(g.lv("yt-remote-auto-connect",this.rV,this));this.subscriptions.push(g.lv("yt-remote-receiver-resumed",this.qV,this));this.subscriptions.push(g.lv("mdx-privacy-popup-confirm",this.HW,this));this.subscriptions.push(g.lv("mdx-privacy-popup-cancel",this.GW,this));this.IM()};
g.k.load=function(){this.player.cancelPlayback();g.VM.prototype.load.call(this);this.gi=new y9(this,this.player,this.Sb);var a=(a=VUa())?a.currentTime:0;var b=v9()?new Q8(p9(),void 0):null;0==a&&b&&(a=M8(R8(b)));0!==a&&this.Wb(a);$Ua(this,this.xd,this.xd);this.player.Xk(6)};
g.k.unload=function(){this.player.ea("mdxautoplaycanceled");this.Ym=this.Nk;(0,g.ie)(this.gi,this.Sb);this.Sb=this.gi=null;g.VM.prototype.unload.call(this);this.player.Xk(5);G9(this)};
g.k.xa=function(){g.mv(this.subscriptions);g.VM.prototype.xa.call(this)};
g.k.Pk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.gi.nj.apply(this.gi,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.vf};
g.k.Gk=function(){return this.Sb?R8(this.Sb).Gk:!1};
g.k.hasNext=function(){return this.Sb?R8(this.Sb).hasNext:!1};
g.k.Wb=function(a,b){this.uL=a||0;this.player.ea("progresssync",a,b);this.player.Ma("onVideoProgress",a||0)};
g.k.getCurrentTime=function(){return this.uL};
g.k.getProgressState=function(){var a=R8(this.Sb),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:this.player.V().N("web_player_mdx_allow_seeking_change_killswitch")?this.player.sf():!a.isAdPlaying()&&this.player.sf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+K8(a):a.B,isAtLiveHead:1>=(a.u?a.i+K8(a):a.i)-this.getCurrentTime(),loaded:a.S,seekableEnd:a.u?a.i+K8(a):a.i,seekableStart:0<
a.C?a.C+K8(a):a.C}};
g.k.nextVideo=function(){this.Sb&&this.Sb.nextVideo()};
g.k.AA=function(){this.Sb&&this.Sb.AA()};
g.k.ST=function(a){1===a&&(this.HF=this.Sb?R8(this.Sb):null)};
g.k.tV=function(){var a=v9()?new Q8(p9(),void 0):null;if(a){var b=this.Ym;this.loaded&&this.unload();this.Sb=a;this.HF=null;b.key!==this.Nk.key&&(this.Ym=b,this.load())}else(0,g.he)(this.Sb),this.Sb=null,this.loaded&&(this.unload(),(a=this.HF)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,M8(a)));this.player.ea("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.IM=function(){var a=[this.Nk],b=a.concat,c=SUa();E8()&&g.Ty("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.xo=b.call(a,c);a=q9()||this.Nk;H9(this,a);this.player.Ma("onMdxReceiversChange")};
g.k.rV=function(){var a=q9();H9(this,a)};
g.k.qV=function(){this.Ym=q9()};
g.k.HW=function(){this.Lw=!0;G9(this);x9=!1;r9&&t9(r9,1);r9=null};
g.k.GW=function(){this.Lw=!1;G9(this);H9(this,this.Nk);this.Ym=this.Nk;x9=!1;r9=null;this.player.playVideo()};
g.k.kf=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.xo;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?G8():H9(this,b)),this.loaded?this.Ym:this.Nk;case "quickCast":return 2===this.xo.length&&"cast-selector-receiver"===this.xo[1].key?(b&&G8(),!0):!1}};
g.k.EG=function(){this.Sb.EG()};
g.k.Li=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.UM("remote",F9);})(_yt_player);
